import AboutFAQ from "@/components/About/AboutFAQ";
import AdvertisingDisclaimer from "@/components/About/AdvertisingDisclaimer";
import Team from "@/components/About/Team";
import Vision from "@/components/About/Vision";
import Container from "@/components/ui/Container";
import generateSEO from "@/lib/seo";
import React from "react";

export const metadata = generateSEO({
  title: "TampaBuzz | About",
  description:
    "This blog accepts forms of cash advertising, sponsorship, paid insertions or other forms of compensation. While the compensation received may influence the topics or posts made in this blog, we always give our honest opinions on those topics. Some advertising is in the form of advertisements generated by a third party ad network while some are ads sourced and sold directly by I Love the Burg. Any advertisements or sponsored posts will be identified as paid advertisements. Md Aminul Islam is a Full stack Passionate developer with experience in React, Next.js, and UI/UX design.",
  url: "https://tampabuzz360.com/about",
  images: ["https://tampabuzz360.com/images/team/aminul.jpg"],
  author: "Syed Tajim Hossain",
  keywords:
    "Tampabuzz 360 Advertising Disclaimer, Advertising Disclaimer of Tampabuzz360, About tampa, Md Aminul Islam, Web developer Aminul, Syed Tajim Hossain",
});

const AboutPage = () => {
  return (
    <Container className="space-y-20">
      <Team />
      <Vision />
      <AboutFAQ />
      <AdvertisingDisclaimer />
    </Container>
  );
};

export default AboutPage;
