import React from "react";
import Title from "../ui/Title";

const AdvertisingDisclaimer = () => {
  return (
    <div className="space-y-2">
      <Title title="Advertising Disclaimer" />
      <p className="text-justify">
        This blog accepts forms of cash advertising, sponsorship, paid
        insertions or other forms of compensation. While the compensation
        received may influence the topics or posts made in this blog, we always
        give our honest opinions on those topics. Some advertising is in the
        form of advertisements generated by a third party ad network while some
        are ads sourced and sold directly by I Love the Burg. Any advertisements
        or sponsored posts will be identified as paid advertisements.
      </p>
    </div>
  );
};

export default AdvertisingDisclaimer;
